#!/bin/bash

set -e

WORKSPACE=/var/lib/go-agent/pipelines/mydockerjava
REGISTRY_URL=10.112.4.102:5000
cp /opt/apache-maven-3.5.0-bin.tar.gz $WORKSPACE/maven
#docker images | grep none | awk '{print $3}'| xargs docker rmi -f
docker build -t oce/maven:3.5.0 $WORKSPACE/maven
if docker ps -a | grep -i maven; then
   docker rm -f maven
fi
docker create --name maven oce/maven:3.5.0
docker cp maven:/hello/target/hello.war $WORKSPACE/hello
docker build -t $REGISTRY_URL/oce/hello:1.0 $WORKSPACE/hello
docker push $REGISTRY_URL/oce/hello:1.0
if docker ps -a | grep -i newhello;then
   docker rm -f newhello
fi
docker run -d -p 80:8080 --name newhello --link oceoracle:linksql $REGISTRY_URL/oce/hello:1.0
exec "$@"
